### ISSUE TITLE
autocatalog: App-pack-gen need to use latest UDS images

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/app-pack-generator#22]
Scope of this ticket is for the app-pack-gen code to be updated with the newest docker containers from U-DS and the app-pack-gen service in **dev** and **test** environments to be updated. Only after successful testing do we want this to go to the operation venues.

success criteria:
- [app-pack-generator templates](https://github.com/unity-sds/app-pack-generator/tree/main/app_pack_generator/templates) are updated with the required stage-out container and **new** environment entry
- App-pack-generator repository is tagged with new release
- unity-app-generator repository is updated with enweest app-pack-gen release
- [unity-app-generator](https://github.com/unity-sds/unity-app-generator) repository is tagged with a new release
- updated application package service is deployed dev environment
- updated application package service is deployed test environment

**Comment by mike-gangl** [comment]
@ngachung - what version of the untity-data-services repo (stage-out) should we be updating to?

**Comment by mike-gangl** [comment]
Sounds like 7.9.0 is the appropriate tag

**Comment by ngachung** [comment]
Yes, 7.9.0 is the correct version.

**Comment by mcduffie** [comment]
Implemented at:
* https://github.com/unity-sds/app-pack-generator/releases/tag/0.4.0
